import { Sora } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Shofiyul Fuad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className=" scroll-smooth">
      <StoreProvider>
        <body className={`${inter.className}`}>{children}</body>
      </StoreProvider>
    </html>
  );
}
